name: Add PR Comment
description: Adds a PR comment on an open PR in another repository
inputs: 
  username:
    required: true
    description: Github Username
  token:
    required: true
    description: Github Password
  repo-name: 
    required: true
    description: The name of the repository the comment is being made in
  pr-number: 
    required: true
    description: Pull Request or Issue Number from api-specs repo
  message: 
    required: true
    description: The message to be used as the PR comment

runs:
  using: "composite"
  steps:
    - name: Make PR Comment
      run: |
        curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/Bandwidth/${{ inputs.repo-name }}/issues/${{ inputs.pr-number }}/comments \
          -u ${{ inputs.username }}:${{ inputs.token }} \
          -d '{"body": "${{ inputs.message }}"}'
      shell: bash
