name: Replace Specs and Snippets
description: Replaces specs with specs from api-specs repository and code-snippets from api-docs-code-snippets repository
inputs: 
  branch-name: 
    required: true
    description: Desired Branch Name
  username: 
    required: true
    description: Github Username
  token: 
    required: true
    description: Github Token

outputs: 
  pr-number: 
    description: "The number of the PR that was opened"
    value: ${{ steps.output-pr-number.outputs.pr-number }}
 
runs:
    using: "composite"
    steps:
      - uses: actions/checkout@v2
        with: 
          token: ${{ inputs.token }}

      - name: Create or Checkout Branch
        id: branch_create
        run: |
          git config user.email "dx@bandwidth.com"
          git config user.name ${{ inputs.username }}
          if [ "$(git ls-remote --heads https://${{ inputs.username }}:${{ inputs.token }}@github.com/Bandwidth/api-docs.git ${{ inputs.branch-name }} | wc -l)" -eq 1 ]
          then
            git fetch
            git checkout ${{ inputs.branch-name }}
          else
            git checkout -b ${{ inputs.branch-name }}
            echo "::set-output name=needs_pr::true"
          fi
        shell: bash

      - name: Copy Api Specs
        run: |
          mkdir api-specs
          if [ "$(git ls-remote --heads https://${{ inputs.username }}:${{ inputs.token }}@github.com/Bandwidth/api-specs.git ${{ inputs.branch-name }} | wc -l)" -eq 1 ]
          then
            git clone --branch ${{ inputs.branch-name }} https://${{ inputs.username }}:${{ inputs.token }}@github.com/Bandwidth/api-specs api-specs
          else
            git clone https://${{ inputs.username }}:${{ inputs.token }}@github.com/Bandwidth/api-specs api-specs
          fi
          rm -r api-specs/.git
          cp -TRv api-specs/external site/specs
          rm -r api-specs
        shell: bash

      - name: Copy Code Snippets
        run: |
          mkdir code-snippets
          if [ "$(git ls-remote --heads https://${{ inputs.username }}:${{ inputs.token }}@github.com/Bandwidth/api-docs-code-snippets.git ${{ inputs.branch-name }} | wc -l)" -eq 1 ]
          then
            git clone --branch ${{ inputs.branch-name }} https://${{ inputs.username }}:${{ inputs.token }}@github.com/Bandwidth/api-docs-code-snippets code-snippets
          else
            git clone https://${{ inputs.username }}:${{ inputs.token }}@github.com/Bandwidth/api-docs-code-snippets code-snippets
          fi
          rm -r code-snippets/.git
          mkdir site/code-snippets
          cp -TR code-snippets/external site/code-snippets
          mv -v code-snippets/add-code-snippets-oas.js code-snippets/package.json code-snippets/env-replace site/code-snippets
          rm -r code-snippets
        shell: bash

      - name: Generate Code Snippets
        run: |
          cd site/code-snippets
          npm install
          node add-code-snippets-oas.js
          cd ..
          git add ./specs/*
          git commit -m "Add Code Snippets to Spec Files"
          git push origin ${{ inputs.branch-name }}
        shell: bash
        
      - name: Open Pull Request
        if: steps.branch_create.outputs.needs_pr
        run: |
          hub pull-request --base Bandwidth:main -m '${{ inputs.branch-name }}' -m 'Update API specs from upstream api-specs repository'
        env:
          GITHUB_TOKEN: ${{ inputs.token }}
        shell: bash

      - name: Output PR Number 
        id: output-pr-number
        run: echo "::set-output name=pr-number::$(hub pr list -h ${{ inputs.branch-name }} -f %I)"
        env:
          GITHUB_TOKEN: ${{ inputs.token }}
        shell: bash
