name: Update Specs
description: Update spec files on an existing PR with specs from api-specs repository
inputs: 
  branch-name: 
    required: true
    description: Desired Branch Name
  username: 
    required: true
    description: Github Username
  token: 
    required: true
    description: Github Token
 
runs:
    using: "composite"
    steps:
      - uses: actions/checkout@v2
        with: 
          token: ${{ inputs.token }}
          ref: ${{ inputs.branch-name }}

      - name: Create and Push Branch
        run: |
          git config user.email "dx@bandwidth.com"
          git config user.name ${{ inputs.username }}
          git checkout ${{ inputs.branch-name }}
          mkdir api-specs
          git clone --branch ${{ inputs.branch-name }} https://${{ inputs.username }}:${{ inputs.token }}@github.com/Bandwidth/api-specs api-specs
          rm -r api-specs/.git
          cp -TRv api-specs/external site/specs
          rm -r api-specs
          git add .
          git commit -m "Update Specs from api-specs repo PR"
          git push
        shell: bash
