describe('Verifying that the Account Management Tab opens and closes', () => {
    it('Should verify that clicking a tab opens and closes the submenu', () => {
        cy.visit('/docs')
        cy.get('a.menu__link')
          .contains('Account Management')
          .should('have.attr', 'aria-expanded') 
          .and('match', /false/)        
        cy.get('a.menu__link')
          .contains("Account Management")
          .click()
          .should('have.attr', 'aria-expanded') 
          .and('match', /true/)
        cy.get('a.menu__link')
          .contains("Account Management")
          .click()
          .should('have.attr', 'aria-expanded') 
          .and('match', /false/)
      })
})

describe('Open Setup Tab under Account Management', () => {
  it('tests the submenu',() => {
    cy.visit('/docs')
    cy.get('a.menu__link')
      .contains("Account Management")
      .click()
    cy.get('a.menu__link')
      .contains('Setup')
      .should('have.attr', 'aria-expanded') 
      .and('match', /false/)        
    cy.get('a.menu__link')
      .contains("Setup")
      .click()
      .should('have.attr', 'aria-expanded') 
      .and('match', /true/)
    cy.get('a.menu__link')
      .contains("Setup")
      .click()
      .should('have.attr', 'aria-expanded') 
      .and('match', /false/)    
    })

}) 

describe('Check the sidebar to make sure tabing works', () => {
    it('Should verify that clicking a tab opens and closes the submenu', () => {
        cy.visit('/docs')
        cy.get('a.menu__link')
          .contains('Numbers')
          .should('have.attr', 'aria-expanded') 
          .and('match', /false/)        
        cy.get('a.menu__link')
          .contains("Numbers")
          .click()
          .should('have.attr', 'aria-expanded') 
          .and('match', /true/)  
        cy.get('a.menu__link')
          .contains("Numbers")
          .click()
          .should('have.attr', 'aria-expanded') 
          .and('match', /false/)  
      })
})    

describe('Check the sidebar to make sure tabing works', () => {
    it('Should verify that clicking a tab opens and closes the submenu', () => {
        cy.visit('/docs')
        cy.get('a.menu__link')
          .contains('Voice')
          .should('have.attr', 'aria-expanded') 
          .and('match', /false/)        
        cy.get('a.menu__link')
          .contains("Voice")
          .click()
          .should('have.attr', 'aria-expanded') 
          .and('match', /true/)  
        cy.get('a.menu__link')
          .contains("Voice")
          .click()
          .should('have.attr', 'aria-expanded') 
          .and('match', /false/)  
      })
})    

describe('Check the sidebar to make sure tabing works', () => {
    it('Should verify that clicking a tab opens and closes the submenu', () => {
        cy.visit('/docs')
        cy.get('a.menu__link')
          .contains('Messaging')
          .should('have.attr', 'aria-expanded') 
          .and('match', /false/)        
        cy.get('a.menu__link')
          .contains("Messaging")
          .click()
          .should('have.attr', 'aria-expanded') 
          .and('match', /true/)  
        cy.get('a.menu__link')
          .contains("Messaging")
          .click()
          .should('have.attr', 'aria-expanded') 
          .and('match', /false/)  
      })
})    

describe('Check the sidebar to make sure tabing works', () => {
    it('Should verify that clicking a tab opens and closes the submenu', () => {
        cy.visit('/docs')
        cy.get('a.menu__link')
          .contains('WebRTC')
          .should('have.attr', 'aria-expanded') 
          .and('match', /false/)        
        cy.get('a.menu__link')
          .contains("WebRTC")
          .click()
          .should('have.attr', 'aria-expanded') 
          .and('match', /true/)  
        cy.get('a.menu__link')
          .contains("WebRTC")
          .click()
          .should('have.attr', 'aria-expanded') 
          .and('match', /false/)  
      })
})    

describe('Check the sidebar to make sure tabing works', () => {
    it('Should verify that clicking a tab opens and closes the submenu', () => {
        cy.visit('/docs')
        cy.get('a.menu__link')
          .contains('Emergency Services')
          .should('have.attr', 'aria-expanded') 
          .and('match', /false/)        
        cy.get('a.menu__link')
          .contains("Emergency Services")
          .click()
          .should('have.attr', 'aria-expanded') 
          .and('match', /true/)  
        cy.get('a.menu__link')
          .contains("Emergency Services")
          .click()
          .should('have.attr', 'aria-expanded') 
          .and('match', /false/)  
      })
})    
