name: 'Push To SDK Repo'
description: 'Pushes updated code to a new branch on the given SDK repo'
inputs:
  repoName:
    description: 'Name of the repo to push to'
    required: true
  unzipPathExtension:
    description: 'An optional path extension for grabbing the unzipped directory. If set, must end in /'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repoName }}
    - ${{ inputs.unzipPathExtension }}
