openapi: 3.0.1
info:
  description: |-
    The API Specification for Bandwidth's Integrations Platform.

    ## Base URL

    `https://integration.bandwidth.com/api/v1`
  title: Integrations
  version: 1.0.0
  contact:
    name: Bandwidth
    url: https://support.bandwidth.com
    email: support@bandwidth.com
security:
  - httpBasic: []
servers:
  - url: https://integrations.bandwidth.com/api/v1
    description: Production
tags:
  - name: Duet
paths:
  /v1/accounts/{accountId}/integrations/duets:
    get:
      tags:
        - Duet
      operationId: listDuets
      parameters:
        - $ref: '#/components/parameters/accountIdPathParam'
        - $ref: '#/components/parameters/sipPeerIdQueryParam'
      responses:
        '200':
          $ref: '#/components/responses/duetArray'
        '400':
          $ref: '#/components/responses/badRequestError'
        '401':
          $ref: '#/components/responses/unauthorizedError'
        '403':
          $ref: '#/components/responses/forbiddenError'
        '404':
          $ref: '#/components/responses/notFoundError'
        '405':
          $ref: '#/components/responses/methodNotAllowedError'
        '429':
          $ref: '#/components/responses/tooManyRequestsError'
        '500':
          $ref: '#/components/responses/internalServerError'
      summary: List duets based on account_id
      description: List duets based on account_id
components:
  responses:
    duetArray:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/duet'
      description: Successfully returning duets.
    duet:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/duet'
      description: Successfully returning duet.
  parameters:
    accountIdPathParam:
      description: Customer ACCOUNT ID.
      in: path
      name: accountId
      required: true
      schema:
        type: integer
        format: int32
    sipPeerIdQueryParam:
      description: Sip Peer Id Query Param.
      in: query
      name: sipPeerId
      schema:
        type: string
  schemas:
    duet:
      type: object
      properties:
        duetName:
          type: string
          example: msteams_dr
        duetDisplay:
          type: string
          example: Microsoft Teams Direct Routing
