openapi: 3.0.3
info:
  title: Test XML API
  version: 1.1.0
  contact:
    name: Bandwidth Support
    email: support@bandwidth.com
    url: https://support.bandwidth.com
  description: >-
    A Test XML API
servers:
  - url: https://xml.bandwidth.com/api/v1
    description: Production
paths:
  /testXml:
    post:
      summary: Test XML
      description: A test XML API definition.
      operationId: testXml
      tags:
        - Test XML
      requestBody:
        $ref: '#/components/requestBodies/sampleXmlRequest'
      responses:
        '200':
          $ref: '#/components/responses/sampleXmlResponse'
components:
  schemas:
    sampleXmlObject:
      type: object
      properties:
        id:
          type: integer
          example: 1
          xml:
            name: Id
        name:
          type: string
          example: TestName
          xml:
            attribute: true
        date:
          type: string
          format: date
          example: 2023-01-03
          xml:
            name: Date
        nestedObject:
          type: object
          properties:
            createdDate:
              type: string
              format: date
              example: 2023-01-03
              xml:
                name: createdDate
            subId:
              type: string
              example: abc123
              xml:
                attribute: True
          xml:
            name: NestedObject
      xml:
        name: XmlObject
  requestBodies:
    sampleXmlRequest:
      content:
        application/xml:
          schema:
            $ref: '#/components/schemas/sampleXmlObject'
  responses:
    sampleXmlResponse:
      description: A sample XML response.
      content:
        application/xml:
          schema:
            $ref: '#/components/schemas/sampleXmlObject'
  securitySchemes:
    Basic:
      type: http
      scheme: basic
      description: >-
        Basic authentication is a simple authentication scheme built into the
        HTTP protocol. To use it, send your HTTP requests with an Authorization
        header that contains the word Basic followed by a space and a
        base64-encoded string `username:password`.

        Example: `Authorization: Basic ZGVtbZpwQDU1dzByZA==`
security:
  - Basic: []
tags:
  - name: Test XML
