name: Rollback Release
description: Takes the latest release and converts it to a draft and then kicks off a workflow dispatch to publish the previous release to AWS.
outputs:
  goodRelease:
    description: The tag of the release that we want to rollback to. 
runs:
  using: 'node16'
  main: 'index.js'
