# Ingest repository_dispatch events for syncing blog posts
name: Blog Posts Listener

on:
  repository_dispatch:
    types: [Blog]

jobs:
  sync-blog-posts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Git and Create Branch
        run: |
          git config user.email "dx@bandwidth.com"
          git config user.name "DX-Bandwidth"
          git checkout -b sync-blog-posts

      - name: Update Blog Posts File
        run: |
          cat > ./site/blogposts.config.json <<< $POSTS_JSON
        env:
          GITHUB_TOKEN: ${{ secrets.DX_GITHUB_TOKEN }}
          POSTS_JSON: ${{ toJson(github.event.client_payload.posts) }}

      - name: Commit Changes and Create Pull Request
        run: |
          git add site/blogposts.config.json
          git commit -m 'update blog posts'
          git push origin sync-blog-posts
          gh pr create -B main -H sync-blog-posts --title 'Update Blog Posts' --body 'Auto-generated by Blog Posts Listener Workflow'
        env:
          GITHUB_TOKEN: ${{ secrets.DX_GITHUB_TOKEN }}
