name: Cypress Nightly on Prod

on:
  schedule:
    - cron: "0 4 * * *"

jobs:
  cypress_nightly:
    name: Cypress Nightly Tests
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
      options: --user 1001 --shm-size=2g
    strategy:
      fail-fast: false
      matrix:
        node-version: [16, 18, 20]
        browser: [chrome]
        exclude:
          - node-version: 16
            browser: firefox
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5.8.0
        timeout-minutes: 40
        with:
          browser: ${{ matrix.browser }}
          working-directory: ./site
          config-file: prod-cypress.config.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify_for_failures:
    name: Notify for Failures
    needs: [cypress_nightly]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack of Failures
        uses: Bandwidth/build-notify-slack-action@v1.0.0
        with:
          job-status: failure
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: ${{ secrets.SLACK_CHANNEL }}
