name: Cypress

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cypress:
    name: Cypress Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: node -v

      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Static Site
        run: |
          cd site
          yarn install --pure-lockfile
          npm run build  

      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0
        timeout-minutes: 40
        with:
          record: true
          parallel: true
          wait-on: http://localhost:3000
          browser: electron
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}