name: Cypress Nightly on Prod
on:
  schedule:
    - cron: '0 4 * * *'

jobs:
  cypress_nightly:
    runs-on: ubuntu-latest      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress nightly tests
        timeout-minutes: 40
        with:
          record: true
          browser: chrome
          start: npm start
          wait-on: https://dev.bandwidth.com/
          wait-on-timeout: 180
          config-file: ./cypress.config.ts
          tag: production          
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # overwrite commit message sent to Dashboard
          COMMIT_INFO_MESSAGE: ${{github.event.pull_request.title}}
          # re-enable PR comment bot
          COMMIT_INFO_SHA: ${{github.event.pull_request.head.sha}}          