name: Cypress

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cypress:
    name: Cypress Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: node -v

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0
        timeout-minutes: 40
        with:
          record: true
          tag: node-${{ matrix.node }}
          parallel: true
          build: npm run build
          start: npm run start-from-build
          wait-on: http://localhost:3000
          browser: electron
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}