name: Cypress Nightly on Prod

on:
  schedule:
    - cron: '0 4 * * *'

jobs:
  cypress_nightly:
    runs-on: ${{ matrix.os }}
    container:
      image: cypress/browsers:node16.13.2-chrome97-ff96
      options: --user 1001 --shm-size=2g     
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        browser: [chrome]   
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: node -v   

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress nightly tests
        uses: cypress-io/github-action@v4.2.0
        timeout-minutes: 40
        with:
          record: true
          browser: ${{ matrix.browser }}
          config-file: ./cypress.config.ts
          tag: production          
        env:
          CYPRESS_host: https://dev.bandwidth.com/
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # overwrite commit message sent to Dashboard
          COMMIT_INFO_MESSAGE: ${{github.event.pull_request.title}}
          # re-enable PR comment bot
          COMMIT_INFO_SHA: ${{github.event.pull_request.head.sha}}