name: Cypress Nightly on Prod
on:
  schedule:
    - cron: '0 4 * * *'
jobs:
  cypress_nightly:
    runs-on: ${{ matrix.os }}
    container:
      image: cypress/browsers:node16.13.2-chrome97-ff96
      options: --user 1001 --shm-size=2g        
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        browser: [chrome, firefox]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress nightly tests
        timeout-minutes: 40
        with:
          record: true
          browser: ${{ matrix.browser }}
          start: npm start
          wait-on: https://dev.bandwidth.com/
          wait-on-timeout: 180
          config-file: ./cypress.config.ts
          tag: production          
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}