name: Lint
on:
  pull_request:
    branches:
    - 'main'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Checkout devx-utils which may contain any custom Spectral rulesets.
      - name: Checkout devx-utils
        uses: actions/checkout@v2
        with:
          repository: Bandwidth/devx-utils
          token: ${{ secrets.BW_GITHUB_PASSWORD }}
          path: devx-utils
      # Run the Spectral on our OpenAPI specs using a custom ruleset.
      - name: Run Spectral
        uses: stoplightio/spectral-action@master
        with:
          file_glob: specs/**/*.{json,yml,yaml}
