# Deploys the doc site to an S3 bucket

name: PR Publish Docsite

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'external/specs/**'
      - 'external/markdown/voice/bxml/bxmlVerbs/**'
      - 'external/markdown/voice/bxml/bxmlCallbacks/**'
      - 'external/markdown/voice/bxml/bxmlAsyncCallbacks/**'
      - 'external/markdown/messaging/callbacks/**'
      - 'external/markdown/dashboard/webhooks/**'

jobs:
  changelog-check:
    name: Validate changelog
    runs-on: ubuntu-latest
    steps:
    - name: Repo Checkout
      uses: actions/checkout@v2
    - name: Confirm Release Notes Update
      uses: dangoslen/changelog-enforcer@v2
      with:
        changeLogPath: 'external/markdown/changelog.md'
        skipLabels: 'no-changelog'
