# Changelog validation

name: PR Changelog

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'site/**'

jobs:
  changelog_validate:
    name: Changelog Validate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Confirm Release Notes Update
      uses: dangoslen/changelog-enforcer@v2
      with:
        changeLogPath: 'site/src/pages/changelog.md'
        skipLabels: 'no-changelog'
