# Deletes the staging docsite bucket on PR closed

name: PR Closed Delete Bucket

on:
  pull_request:
    types: [closed]

jobs:
  delete_bucket:
    name: Delete Bucket
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Create Bucket Name
      id: create_name
      run: |
        BUCKET_NAME=bw-api-docs-${GITHUB_HEAD_REF#refs/heads/}
        BUCKET_NAME=$(echo "$BUCKET_NAME" | tr '[:upper:]' '[:lower:]') #convert to lowercase for AWS bucket (can't be uppercase)
        BUCKET_NAME=$(echo "$BUCKET_NAME" | sed -e "s/[^a-z0-9]/-/g") #replace all remaining non alphanumerics with -
        echo $BUCKET_NAME
        echo "::set-output name=bucket_name::$BUCKET_NAME"
    - name: Delete Bucket
      run: |
        aws s3 rb s3://$BUCKET_NAME --force --region us-east-1
      env:
        BUCKET_NAME: ${{ steps.create_name.outputs.bucket_name }}
