# Validates the python code

name: PR Validate Python
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'site/code-snippets/**/*.py'
jobs:
  validate:
    name: Validate Python
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Validate Python
      uses: ./.github/actions/validate-python
      env:
        BW_USERNAME: ${{ secrets.BW_USERNAME }}
        BW_PASSWORD: ${{ secrets.BW_PASSWORD }}
        BW_ACCOUNT_ID: ${{ secrets.BW_ACCOUNT_ID }}
        BW_MESSAGING_APPLICATION_ID: ${{ secrets.BW_MESSAGING_APPLICATION_ID }}
        BW_VOICE_APPLICATION_ID: ${{ secrets.BW_VOICE_APPLICATION_ID }}
        BW_MFA_MESSAGING_APPLICATION_ID: ${{ secrets.BW_MFA_MESSAGING_APPLICATION_ID }}
        BW_MFA_VOICE_APPLICATION_ID: ${{ secrets.BW_MFA_VOICE_APPLICATION_ID }}
        BW_NUMBER: ${{ secrets.BW_NUMBER }}
        BW_MFA_NUMBER: ${{ secrets.BW_MFA_NUMBER }}
        USER_NUMBER: ${{ secrets.USER_NUMBER }}
