# Validates the python code

name: PR Validate Python
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'site/sample-python/**/*.py' 
      #- 'site/code-snippets/**/*.py' #I hope this works
jobs:
  validate:
    name: Validate Python
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Validate Python
      uses: ./.github/actions/validate-python
      env:
        PRINT_ME: 'ayy lmao it works'
