# Validates the python code

name: PR Validate Python
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'site/code-snippets/**/*.py'
jobs:
  validate:
    name: Validate Python
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Validate Python
      uses: ./.github/actions/validate-python
