name: PR Validate C#
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'site/code-snippets/**/*.cs'
jobs:
  validate:
    name: Validate C#
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Download Bandwidth SDK and compile snippets
      run: |
        for f in $(find site/code-snippets -name 'Program.cs')
        do
          # Save off the existing file as a temporary file.
          mv $f Temp.cs
          
          # Create a default console application.
          dotnet new console

          # Overwrite the default console application file with our temporary file.
          mv Temp.cs $f

          # Add the Bandwidth SDK into our project.
          dotnet add package Bandwidth.Sdk

          # Build our console application.
          dotnet build
        done
