# Publishes an update to the docsite
# This is a temporary filler workflow

name: Docsite Update

on:
  push:
    branches:
      - 'main'
    paths:
      - 'specs/*'
      - 'markdown/*'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'specs/*'
      - 'markdown/*'
jobs:
  docsite-publish:
    name: Publish docsite
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo hello world
