# Deploys the doc site to an S3 bucket

name: Publish Docsite

on:
  push:
    branches:
      - 'main'
    paths:
      - 'external/specs/**'
      - 'external/markdown/**'
  workflow_dispatch:

jobs:
  publish:
    name: Publish Docsite
    runs-on: ubuntu-latest
    steps:
    - name: Repo Checkout
      uses: actions/checkout@v2
    - name: NPM install
      run: npm install
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Generate Doc Portal
      run: npm run generate-docsite-external
    - name: Create Bucket
      run: |
        echo $BUCKET_NAME
        aws s3 mb s3://$BUCKET_NAME --region us-east-1
      env:
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
    - name: Sync zip to Bucket
      run: |
        aws s3 sync ./external/portal s3://$BUCKET_NAME --acl public-read
      env:
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
