#Workflow that pushes our resources (OpenAPI specs and Postman collections) to their public repos
name: Publish Resources

on:
  push:
    branches:
      - 'main'
    paths:
      - 'specs/**'
      - 'postman/**'


jobs:
  publish-oas:
    name: Publish OpenAPI Specs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code into VM
      uses: actions/checkout@v2
    - name: Push openapi specs
      uses: ./.github/actions/publish-specs
      env:
        DX_GIT_USER: ${{ secrets.BW_GITHUB_USERNAME }}
        DX_GIT_TOKEN: ${{ secrets.BW_GITHUB_PASSWORD }}
        DX_GIT_EMAIL: ${{ secrets.DX_GIT_EMAIL }}
        SPECS_DIRECTORY: 'specs'
  publish-postman:
    name: Publish Postman Collection
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code into VM
      uses: actions/checkout@v2
    - name: install npm package.json
      run: 'npm install'
    - name: Generates the postman collection
      run: 'npm run postman'
    - name: Push postman collection
      uses: ./.github/actions/publish-postman
      env:
        DX_GIT_USER: ${{ secrets.BW_GITHUB_USERNAME }}
        DX_GIT_TOKEN: ${{ secrets.BW_GITHUB_PASSWORD }}
        DX_GIT_EMAIL: ${{ secrets.DX_GIT_EMAIL }}
        POSTMAN_FILE: 'postman/postman.json'
