# Publishes SDK updates to the appropriate repos

name: Publish SDKs

on:
#  push:
#    branches:
#      - 'main'
#    paths:
#      - 'specs/**'
  push:
    branches:
      - 'task/bandwidth-sdks-integration'

    
jobs:
  publish-sdks:
    name: Publish sdks
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        include:
        - generateCommand: '-l python'
          repoName: 'python-sdk'
          ignoreFiles: 'README.md'
        - generateCommand: '-l ruby'
          repoName: 'ruby-sdk'
          ignoreFiles: 'README.md'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate SDK
      run: 'npm run generate -- ${{ matrix.generateCommand }}'
    - name: Push SDK
      uses: ./.github/actions/push-to-sdk-repo
      with:
        repoName: ${{ matrix.repoName }}
        ignoreFiles: ${{ matrix.ignoreFiles }}
      env:
        #BW_GITHUB_USERNAME: ${{ secrets.BW_GITHUB_USERNAME }}
        #BW_GITHUB_PASSWORD: ${{ secrets.BW_GITHUB_PASSWORD }}
        BW_GITHUB_EMAIL: ${{ secrets.DX_GIT_EMAIL }}
        BW_GITHUB_USERNAME: 'no'
        BW_GITHUB_PASSWORD: 'u' 
