# Publishes SDK updates to the appropriate repos

name: Publish SDKs

on:
  push:
    branches:
      - 'main'
    paths:
      - 'specs/**'

    
jobs:
  publish-sdks:
    name: Publish sdks
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        include:
        - generateCommand: '-l python'
          repoName: 'python-sdk'
          ignoreFiles: 'README.md'
          unzipPathExtension: ""
        - generateCommand: '-l ruby'
          repoName: 'ruby-sdk'
          ignoreFiles: 'README.md'
          unzipPathExtension: ""
        - generateCommand: '-l phpold'
          repoName: 'php-sdk'
          ignoreFiles: 'README.md'
          unzipPathExtension: ""
        - generateCommand: '-l php'
          repoName: 'php-sdk'
          ignoreFiles: 'README.md'
          unzipPathExtension: ""
        - generateCommand: '-l node -s WebRtc'
          repoName: 'node-webrtc'
          ignoreFiles: 'README.md'
          unzipPathExtension: "WebRtc/"
        - generateCommand: '-l node -s Voice'
          repoName: 'node-voice'
          ignoreFiles: 'README.md'
          unzipPathExtension: "Voice/"
        - generateCommand: '-l node -s TwoFactorAuth'
          repoName: 'node-mfa'
          ignoreFiles: 'README.md'
          unzipPathExtension: "TwoFactorAuth/"
        - generateCommand: '-l node -s Messaging'
          repoName: 'node-messaging'
          ignoreFiles: 'README.md'
          unzipPathExtension: "Messaging/"
        - generateCommand: '-l node -s Iris'
          repoName: 'node-numbers'
          ignoreFiles: 'README.md'
          unzipPathExtension: "Iris/"
        - generateCommand: '-l java'
          repoName: 'java-sdk'
          ignoreFiles: 'README.md pom.xml'
          unzipPathExtension: ""
        - generateCommand: '-l csharp'
          repoName: 'csharp-sdk'
          ignoreFiles: 'README.md'
          unzipPathExtension: ""
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate SDK
      run: 'npm run generate -- ${{ matrix.generateCommand }}'
    - name: Push SDK
      uses: ./.github/actions/push-to-sdk-repo
      with:
        repoName: ${{ matrix.repoName }}
        ignoreFiles: ${{ matrix.ignoreFiles }}
        unzipPathExtension: ${{ matrix.unzipPathExtension }}
      env:
        BW_GITHUB_USERNAME: ${{ secrets.BW_GITHUB_USERNAME }}
        BW_GITHUB_PASSWORD: ${{ secrets.BW_GITHUB_PASSWORD }}
        BW_GITHUB_EMAIL: ${{ secrets.DX_GIT_EMAIL }}
