# Publishes SDK updates to the appropriate repos

name: Publish SDKs

on:
#  push:
#    branches:
#      - 'main'
#    paths:
#      - 'specs/**'
  push:
    branches:
      - 'task/bandwidth-sdks-integration'

    
jobs:
  publish-sdks:
    name: Publish sdks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - sdkRepo: 'python-sdk'
          run: 'echo python'
          ignoreFiles: 'README.md asdf'
        - sdkRepo: 'node-mfa'
          run: 'echo node mfa'
          ignoreFiles: 'README.md'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run test
      run: ${{ matrix.run }}
    - name: Echo test
      run: 'echo ${{ matrix.ignoreFiles }}'
#    - name: Generate Python SDK
#      run: 'npm run generate -- -l python'
#    - name: Push Python SDK
#      uses: ./.github/actions/push-to-sdk-repo
#      with:
#        repoName: "python-sdk"
#        ignoreFiles: "README.md"
#      env:
#        BW_GITHUB_USERNAME: ${{ secrets.BW_GITHUB_USERNAME }}
#        BW_GITHUB_PASSWORD: ${{ secrets.BW_GITHUB_PASSWORD }}
#        BW_GITHUB_EMAIL: ${{ secrets.DX_GIT_EMAIL }}
#    - name: Generate SDK
#      run: 'npm run generate -- -l ruby'
#    - name: Push SDK
#      uses: ./.github/actions/push-to-sdk-repo
#      with:
#        repoName: "ruby-sdk"
#        ignoreFiles: "README.md"
#      env:
#        BW_GITHUB_USERNAME: ${{ secrets.BW_GITHUB_USERNAME }}
#        BW_GITHUB_PASSWORD: ${{ secrets.BW_GITHUB_PASSWORD }}
#        BW_GITHUB_EMAIL: ${{ secrets.DX_GIT_EMAIL }}
