#Workflow that pushes OpenAPI specs and Postman collections to the Bandwidth Examples repo
name: Push Specs

on:
  push:
    branches:
      - 'main'

jobs:
  push-oas:
    name: Pushes OpenAPI specs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code into VM
      uses: actions/checkout@v2
    - name: Push openapi specs
      uses: ./.github/actions/push-directory-to-examples
      env:
        DX_GIT_USER: ${{ secrets.DX_GIT_USER }}
        DX_GIT_TOKEN: ${{ secrets.DX_GIT_TOKEN }}
        DX_GIT_EMAIL: ${{ secrets.DX_GIT_EMAIL }}
        EXAMPLES_DIRECTORY: 'public-specs'
        BANDWIDTH_SDKS_DIRECTORY: 'specs'
  push-postman:
    name: Pushes Postman Collection
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code into VM
      uses: actions/checkout@v2
    - name: install npm package.json
      run: 'npm install'
    - name: Generates the postman collection
      run: 'npm run postman'
    - name: Push postman collections
      uses: ./.github/actions/push-file-to-examples
      env:
        DX_GIT_USER: ${{ secrets.DX_GIT_USER }}
        DX_GIT_TOKEN: ${{ secrets.DX_GIT_TOKEN }}
        DX_GIT_EMAIL: ${{ secrets.DX_GIT_EMAIL }}
        EXAMPLES_DIRECTORY: 'postman-collections'
        BANDWIDTH_SDKS_FILE: 'postman/postman.json'
