# Updates the latest Published release to a draft release and then kicks off a dispatch to republish the prior published release to AWS

name: Rollback Release

on:
  workflow_dispatch:

jobs:
  rollback:
    name: Rollback Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install Dependencies
      run: |
          cd ./.github/actions/rollback_release
          npm install

    - name: Update the Bad Release to a Draft
      uses: ./.github/actions/rollback_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
