# Updates the latest Published release to a draft release and then kicks off a dispatch to republish the prior published release to AWS

name: Rollback Release

on:
  workflow_dispatch:

jobs:
  rollback:
    name: Rollback Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Update the bad release to a draft
      uses: ./.github/actions/rollback_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
