# Validates the OpenAPI specs in this repo

name: OAS Validate

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'site/specs-source/**'

jobs:
  create-matrix:
    name: Create Matrix From Spec Files
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get List of Changed Files
        id: changed-files
        run: |
          matrix="{\"include\": ["
          changedFiles=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)
          IFS=' ' read -r -a changedFilesArray <<< "$changedFiles"
          for file in "${changedFilesArray[@]}"
          do
            if [[ $file == site/specs-source* ]]
            then
              matrix="${matrix}{\"specs\": \"${file##*/}\"}, "
            fi
          done
          matrix="${matrix%??}]}"
          echo "::set-output name=matrix::$matrix"
        shell: bash

  validate:
    name: Spec Validate
    runs-on: ubuntu-latest
    needs: create-matrix
    strategy:
      matrix: ${{ fromJson(needs.create-matrix.outputs.matrix) }}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Spec
        uses: stoplightio/spectral-action@v0.7.3
        with:
          file_glob: ./site/specs/${{ matrix.specs }}
