# Validates the spec in this repo

name: OAS Validate

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'site/specs-source/**'

jobs:
  validate:
    name: Spec validate
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2

      - name: Validate spec
        uses: stoplightio/spectral-action@v0.7.0
        with:
          file_glob: specs/**/*.{json,yml,yaml}
