# Validates the OpenAPI specs in this repo

name: OAS Validate

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'site/specs-source/**'

jobs:
  create_matrix:
    name: Create Matrix From Spec Files
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setmatrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Matrix Creation Script
        id: setmatrix
        uses: ./.github/actions/create_spec_matrix

  validate:
    name: Spec Validate
    runs-on: ubuntu-latest
    needs: create_matrix
    strategy:
      matrix: ${{fromJson(needs.create_matrix.outputs.matrix)}}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Validate Spec
      #   uses: stoplightio/spectral-action@v0.7.3
      #   with:
      #     file_glob: ./site/specs-source/${{ matrix.specs }}
