# Publishes the spec in this repo

name: SDK Publish

on:
  push:
    branches:
    - 'main'

jobs:
  sdk-publish:
    name: Publish spec
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2
      - name: Devx Utils Checkout
        uses: actions/checkout@v2
        with:
          repository: 'Bandwidth/devx-utils-actions'
          path: 'devx-utils'
          token: ${{ secrets.BW_GITHUB_PASSWORD }}
      - name: Run push
        uses: ./devx-utils/push
        with:
          specPath: './specs'
          githubEmail: 'jmulford@bandwidth.com'
        env:
          BW_GITHUB_USERNAME: ${{ secrets.BW_GITHUB_USERNAME }} 
          BW_GITHUB_PASSWORD: ${{ secrets.BW_GITHUB_PASSWORD }}
          APIMATIC_ACCESS_TOKEN: ${{ secrets.APIMATIC_ACCESS_TOKEN }}
