# Validates the spec in this repo

name: OAS Validate

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'external/specs/**'

jobs:
  validate:
    name: Spec validate
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2
      - name: Devx Utils Checkout
        uses: actions/checkout@v2
        with:
          repository: 'Bandwidth/devx-utils-actions'
          path: 'devx-utils'
          token: ${{ secrets.BW_GITHUB_PASSWORD }}
      - name: Validate spec
        uses: ./devx-utils/validate
        with:
          specPath: './external/specs'
        env:
          BW_GITHUB_USERNAME: ${{ secrets.BW_GITHUB_USERNAME }}
          BW_GITHUB_PASSWORD: ${{ secrets.BW_GITHUB_PASSWORD }} 
          APIMATIC_ACCESS_TOKEN: ${{ secrets.APIMATIC_ACCESS_TOKEN }}
