name: Validate C#
on:
  schedule:
    - cron: '0 6 * * *'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'site/code-snippets/**/*.cs'
  workflow_dispatch:

jobs:
  validate:
    name: Validate C#
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Download Bandwidth SDK and compile snippets
      run: |
        for f in $(find site/code-snippets -name '*.cs')
        do
          # Move into the current file's directory.
          cd "$(dirname $f)"

          # Save off the existing file as a temporary file.
          mv "$(basename $f)" Temp.cs
          
          # Create a default console application.
          dotnet new console

          # Overwrite the default console application file with our temporary file.
          mv Temp.cs "$(basename $f)"

          # Add the Bandwidth SDK into our project.
          dotnet add package Bandwidth.Sdk

          # Build our console application.
          dotnet build

          # Move back to the previous directory.
          cd -
        done
