# Validates the php code

name: Validate PHP
on:
  schedule:
    - cron: '0 6 * * *'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'site/code-snippets/**/*.php'
jobs:
  validate:
    name: Validate PHP
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Validate PHP
      uses: ./.github/actions/validate-php
      env:
        BW_USERNAME: ${{ secrets.BW_USERNAME }}
        BW_PASSWORD: ${{ secrets.BW_PASSWORD }}
        BW_ACCOUNT_ID: ${{ secrets.BW_ACCOUNT_ID }}
        BW_MESSAGING_APPLICATION_ID: ${{ secrets.BW_MESSAGING_APPLICATION_ID }}
        BW_VOICE_APPLICATION_ID: ${{ secrets.BW_VOICE_APPLICATION_ID }}
        BW_MFA_MESSAGING_APPLICATION_ID: ${{ secrets.BW_MFA_MESSAGING_APPLICATION_ID }}
        BW_MFA_VOICE_APPLICATION_ID: ${{ secrets.BW_MFA_VOICE_APPLICATION_ID }}
        BW_NUMBER: ${{ secrets.BW_NUMBER }}
        BW_MFA_NUMBER: ${{ secrets.BW_MFA_NUMBER }}
        USER_NUMBER: ${{ secrets.USER_NUMBER }}
        VOICE_CALLBACK_URL: ${{ secrets.VOICE_CALLBACK_URL }}
